### ISSUE TITLE
mm_fit_signatures Error

### ISSUE THREAD

**Issue by parvathisudha** [bachisiozic/mmsig#1]
Hi,

I am trying to use music on the WGS data. My files were in hg38, and I lifted over to hg19.

I am getting an error: Error in if (sum(abs(alpha - old_alpha)) < 0.00001) { :
missing value where TRUE/FALSE needed

Command used :

```
sig_out <- mm_fit_signatures(muts.input=HT_SNVS_mmsig_hg19, 
                             sig.input=signature_ref,
                             input.format = "vcf",
                             sample.sigt.profs = NULL, 
                             strandbias = TRUE,
                             bootstrap = TRUE,
                             iterations = 100, # 1000 iterations recommended for stable results
                             refcheck=TRUE,
                             cos_sim_threshold = 0.01,
                             force_include = c("SBS13", "SBS-MM1"),
                             dbg=TRUE)
```
Error:
[1] "defaulting to use all signatures in the provided reference"
[1] "colnames sample.consigts.defn (before em)"
[1] "tri" "SBS1" "SBS2" "SBS5" "SBS8" "SBS9" "SBS13" "SBS18" "SBS35" "SBS84" "SBS-MM1"
Error in if (sum(abs(alpha - old_alpha)) < 0.00001) { :
missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In mut.to.sigs.input(mut.ref = muts.input, sample.id = "sample", :
Check ref bases -- not all match context:
Sample1:chr15:22789098:A:T, Sampl5:chr14:107179050:T:G, Sample7:chr1:5935162:T:A,  [... truncated]
2: In lapply(X = X, FUN = FUN, ...) : NAs introduced by coercion

attached packages:
[1] mmsig_0.0.0.9000

Can you please help me to solve this issue?

Thanks
Parvathi.

**Comment by bachisiozic** [comment]
Hi,
Could you send me an extract of your input file in private?

**Comment by parvathisudha** [comment]
Can you please share your email id?

**Comment by bachisiozic** [comment]
bxz262@miami.edu

**Comment by bachisiozic** [comment]
Hi, 
before to run mm_fit_signatures, you have to define the signature object. If you want to run all signature, you have to create this object:
```
sig_ref <- signature_ref[,c("sub", "tri", "SBS1","SBS2","SBS5","SBS8", 
                           "SBS9","SBS13","SBS18","SBS35","SBS-MM1","SBS-MM1")]
```

**Comment by parvathisudha** [comment]
Thanks for the help! 

I got another question. Do you have a hg38 version for this?

**Comment by bachisiozic** [comment]
You are welcome!!
We are working to integrate the hg38 version.
